icon_url: https://music-assistant.io/assets/icon.png
screenshots: [
  "https://music-assistant.io/screenshots/screenshot1.png",
  "https://music-assistant.io/screenshots/screenshot2.png"
],
categories:
  - Media
tags:
  - music
  - media
  - assistant
