icon_url: https://music-assistant.io/assets/icon.png
screenshots:
  - "https://music-assistant.io/assets/banner.png"
  - "https://music-assistant.io/assets/screenshots/screen2.png"
  - "https://music-assistant.io/assets/screenshots/screen3.png"
  - "https://music-assistant.io/assets/screenshots/screen4.png"
categories:
  - Media
tags:
  - music
  - media
  - assistant
