apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "music-assistant.fullname" . }}
  labels:
    app: {{ include "music-assistant.name" . }}
    chart: {{ include "music-assistant.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "music-assistant.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "music-assistant.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.storage.path }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: EXTERNAL_INTERFACE
              value: {{ .Values.externalInterface.interface }}
      volumes:
        - name: storage
          hostPath:
            path: {{ .Values.storage.path }}
            type: DirectoryOrCreate
