apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-assistant
  template:
    metadata:
      labels:
        app: music-assistant
    spec:
      containers:
        - name: music-assistant
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 80
          env:
            - name: INTERFACE
              value: "{{ .Values.interface }}"
